namespace ShipCommander
{
    /// <summary>
    /// Plugin metadata constants.
    /// In NuGet-based setups these are auto-generated by BepInEx.PluginInfoProps,
    /// but since we reference BepInEx DLLs directly, we define them manually.
    /// </summary>
    internal static class PluginInfo
    {
        public const string PLUGIN_GUID = "com.ctoto.lethalmalfunctions";
        public const string PLUGIN_NAME = "LethalMalfunctions";
        public const string PLUGIN_VERSION = "1.0.5";
    }
}
